name: Deploy to GitHub Pages

on:
  push:
    branches: [main] 
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Compute base-href
        id: base
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY%%/*}"
          if [ "$REPO_NAME" = "$OWNER.github.io" ]; then
            echo "BASE=/" >> $GITHUB_OUTPUT
          else
            echo "BASE=/$REPO_NAME/" >> $GITHUB_OUTPUT
          fi

      - name: Build Angular
        run: pnpm exec ng build --base-href='${{ steps.base.outputs.BASE }}'

      - name: Add 404.html (SPA fallback)
        run: |
          OUT=dist/talycap/browser
          cp "$OUT/index.html" "$OUT/404.html"

      - name: Add SPA fallback + disable Jekyll
        run: |
          OUT=dist/talycap/browser
          cp "$OUT/index.html" "$OUT/404.html"
          touch "$OUT/.nojekyll"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/talycap/browser
